### ISSUE TITLE
UI problem on MacOS with com.apple.laf.AquaLookAndFeel

### ISSUE THREAD

**Issue by scharf** [sibvisions/jvx.kitchensink#6]
I have tried the app on my mac and a lot of the controls do not really work as expected. It turns out, that there is a problem with 

With `UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel")` the application works much better. 

For example the *Tabs* container is empty on MacOS and  causes a NPE (using the `UIManager.getSystemLookAndFeelClassName()` which is `com.apple.laf.AquaLookAndFeel`) :

```
java.lang.NullPointerException
	at javax.swing.JComponent.repaint(JComponent.java:4808)
	at com.sibvisions.rad.ui.swing.ext.JVxTabbedPane.setClosableAt(JVxTabbedPane.java:935)
	at com.sibvisions.rad.ui.swing.impl.container.SwingTabsetPanel.setClosableAt(SwingTabsetPanel.java:270)
	at javax.rad.genui.container.UITabsetPanel.setClosableAt(UITabsetPanel.java:197)
	at com.sibvisions.kitchensink.samples.containers.TabsetPanelSample.getContent(TabsetPanelSample.java:95)
...
```

With `jvx 2.6` I get a very similar error 

```
java.lang.NullPointerException
	at javax.swing.JComponent.repaint(JComponent.java:4808)
	at com.sibvisions.rad.ui.swing.ext.JVxTabbedPane.setClosableAt(JVxTabbedPane.java:935)
	at com.sibvisions.rad.ui.swing.impl.container.SwingTabsetPanel.setClosableAt(SwingTabsetPanel.java:270)
	at javax.rad.genui.container.UITabsetPanel.setClosableAt(UITabsetPanel.java:197)
	at com.sibvisions.kitchensink.samples.containers.TabsetPanelSample.getContent(TabsetPanelSample.java:95)
...
```

**Comment by RobertZenz** [comment]
Mh, seems more like JVx problem itself, less of the Kitchensink. I've [created ticket #1754 in the JVx bug tracker](https://oss.sibvisions.com/index.php?do=details&task_id=1754) for the specific NullPointerException.

I'll see that I can get my hand on an Apple machine to do some further testing on this, I've also [created ticket #1755](https://oss.sibvisions.com/index.php?do=details&task_id=1755) as a tracking ticket for testing of the AquaLookAndFeel.

As all these problems are JVx related, and not Kitchensink specific, I'll be closing this issue. Please see the mentioned JVx tickets for progress and further discussion.
